### ISSUE TITLE
Loading the mix view fails when a track has been removed just beforehand

### ISSUE THREAD

**Issue by suterma** [suterma/replayer-pwa#94]
When a set of tracks has been loaded, but one is removed in the edit view, a subsequent change to the mix view fails:

```
tations.ts:103 ERROR: TypeError: Cannot read properties of undefined (reading 'trackDuration')
eval @ mutations.ts:103
wrappedMutationHandler @ vuex.esm-browser.js:315
commitIterator @ vuex.esm-browser.js:1005
eval @ vuex.esm-browser.js:1004
_withCommit @ vuex.esm-browser.js:1162
commit @ vuex.esm-browser.js:1003
boundCommit @ vuex.esm-browser.js:940
eval @ main.ts:38
MultitrackHandler.ts:121 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trackDuration')
    at eval (MultitrackHandler.ts:121:1)
    at Array.map (<anonymous>)
    at Proxy.getAllTrackDuration (MultitrackHandler.ts:120:1)
    at Proxy.render (Compilation.vue:199:1)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5720:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:1)
    at instance.update (runtime-core.esm-bundler.js:5763:1)
    at updateComponent (runtime-core.esm-bundler.js:5588:1)
    at processComponent (runtime-core.esm-bundler.js:5521:1)
 
```
The problem is most likely, that the `this.getAllTrackInstances();` in the MultitrackHandler was not updated according to the deleted track.

Create a Cypress test for this situation.

**Comment by suterma** [comment]
The mix view will be fully rewritten and has been currently removed.
